### PR TITLE
Travis CI support

### PR DESCRIPTION
**Pull request by avodonosov**

### CODE REVIEW

**Comment by stassats** [comment]
Will accept the same but for github actions.

**Comment by avodonosov** [comment]
What advantages github actions have over Travis CI? 

Also, merging the Travis CI solution does not prevent anyhow possible future transition to github actions, even more, some useful building blocks would be available for anyone who is interested to implement github actions.

**Comment by stassats** [comment]
I prefer github actions, and I don't want two CIs to keep track of.

**Comment by avodonosov** [comment]
@stassats , well, as soon as Travis starts demanding attention, you can just remove it and return to the "no trouble" status quo.

Speaking of me personally, I only have rare occasions to work on such issues. My previous approach to this issue was on Jan 3 - #109. At the second approach (the current PR) I managed to drive it this far. Can not say anything about the future.

**Comment by stassats** [comment]
A CI for drakma is not that necessary, it's not like it's changing everyday.

**Pull request closed without merging**
