### PR TITLE
Use quri instead of puri

### PR DESCRIPTION
**Pull request by tmccombs**

### CODE REVIEW

**Comment by hanshuebner** [comment]
Nice, thanks!  Has the required PURI pull request been merged and released to quicklisp?

**Comment by tmccombs** [comment]
It has been merged, I don't know if it has been released to quickly special
yet.

**Comment by tmccombs** [comment]
the quicklisp source for quri is just the master branch of git, so it should be released with the next release of quicklisp.

**Comment by tmccombs** [comment]
yes it has been released to quicklisp

**Comment by hanshuebner** [comment]
Merged, thanks!

**Comment by hanshuebner** [comment]
Xach tried to compile the quicklisp dist with the new version of Hunchentoot and found many systems fail because they somehow depended on PURI:URI's being accepted or returned by HTTP-REQUEST or on PURI to be loaded as dependency of DRAKMA.  It seems that it would be prudent to either fork DRAKMA for QURI support or to add a compatibility layer.  For the time being, your changes had to be pulled back, sorry.

**Comment by tmccombs** [comment]
ok, it looks like I made some bad assumptions about how similar quri is to puri (for example puri returns a keyword for the scheme but quri returns a string). I will work on fixing those things. I don't thing hunchentoot actually depends on drakma using puri, my changes just broke drakma.

**Pull request merged**
